export const CATEGORY__SUCCESS = "CATEGORY__SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";
export const CATEGORY__LOADING = "CATEGORY__LOADING";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
