export const ADD_CHANGE_CATEGORY = "ADD_CHANGE_CATEGORY";
export const ADD_CHANGE_CATEGORY_SUCCESS = "ADD_CHANGE_CATEGORY_SUCCESS";
export const ADD_CHANGE_CATEGORY_FAIL = "ADD_CHANGE_CATEGORY_FAIL";
