export const ADD_CHANGE_CATEGORY = "ADD_CHANGE_CATEGORY";
export const ADD_CHANGE_CATEGORY_SUCCESS = "ADD_CHANGE_CATEGORY_SUCCESS";
export const ADD_CHANGE_CATEGORY_FAIL = "ADD_CHANGE_CATEGORY_FAIL";
export const ADD_CHANGE_RATING = "ADD_CHANGE_RATING";
export const ADD_CHANGE_PRICE = "ADD_CHANGE_PRICE";
export const ADD_CHANGE_BRAND = "ADD_CHANGE_BRAND";
export const ADD_CHANGE_PAGE = "ADD_CHANGE_PAGE";
