export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const IS_LOGING = "IS_LOGING";
export const GET_ME = "GET_ME";
export const USER_REGISTER = "";
export const USER_REGISTER_SUCCESS = "";
export const USER_REGISTER_FAIL = "";

export const USER_UPDATE_INFO = "USER_UPDATE_INFO";
export const USER_CHANGE_PASSWORD = "USER_CHANGE_PASSWORD";
export const USER_UPDATE_INFO_SUCCESS = "USER_UPDATE_INFO_SUCCESS";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
